# Generated by Django 5.2.4 on 2025-07-08 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choice',
            name='name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
