# Generated by Django 5.2.4 on 2025-07-08 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_choice_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='choice',
            name='name',
        ),
    ]
